### ISSUE TITLE
This is the big shit ...

### ISSUE THREAD

**Issue by timothylhuillier** [valanz/pizzawesome#1]
It doesn't work, WTF ?

Are You dev, seriously ?

![verybadtrip](https://cloud.githubusercontent.com/assets/2414729/10879924/57d3187a-8157-11e5-85b0-8a2ef6951580.gif)

**Comment by Nek-** [comment]
![english_motherfucker_do_you_speak_it_by_h311man-d774bf9](https://cloud.githubusercontent.com/assets/972456/10879979/bf703d28-8157-11e5-9bd1-9363c34d9717.jpg)
